SMTPSenderRefused
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-72aad83616asm14844426b3a.76 - gsmtp', 'noreply@codecraft.com')

Traceback (most recent call last)
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/app.py", line 398, in register
mail.send(msg)
^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask_mail/__init__.py", line 540, in send
message.send(connection)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask_mail/__init__.py", line 482, in send
connection.send(self)
^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/Website-Editor/.pythonlibs/lib/python3.12/site-packages/flask_mail/__init__.py", line 177, in send
self.host.sendmail(
^
File "/nix/store/nb21sc3npfc8gvazwnrjxpvb5d48jysx-python3-3.12.7/lib/python3.12/smtplib.py", line 876, in sendmail
raise SMTPSenderRefused(code, resp, from_addr)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0 https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-72aad83616asm14844426b3a.76 - gsmtp', 'noreply@codecraft.com')
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it.

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.